### PR TITLE
Allowing phpunit 5, removing phpunit from requires (wrong)

### PR DESCRIPTION
**Pull request by Ocramius**

### CODE REVIEW

**Comment by DASPRiD** [comment]
Well, errors out, although differently now :)… Apparently it install PHPUnit 5 on 5.5, even though it doesn't meat the requirement of PHP 5.6…

**Comment by Ocramius** [comment]
>  Apparently it install PHPUnit 5 on 5.5, even though it doesn't meat the requirement of PHP 5.6…

That's a PHPUnit bug, I suppose.

**Comment by DASPRiD** [comment]
More like composer bug, now? I mean, the composer.json of PHPUnit 5 says it requires 5.6, so why does composer install it?

**Comment by DASPRiD** [comment]
@Ocramius any update on this?

**Comment by DASPRiD** [comment]
Thanks a lot :)

**Pull request merged**
